### PR TITLE
improve meta server to reply ERR_BUSY for config sync if is updating …

### PR DESCRIPTION
**Pull request by qinzuoyan**
…config to zk, refer to #504

refer to https://github.com/imzhenyu/rDSN/issues/504

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , is it the step of committing changes to dist.service?
- create pull request in rDSN.dist.service
- merge the pull request in rDSN.dist.service
- in rDSN, run 'git submodule update --remote', and create pull request
- merge the pull request in rDSN

**Comment by imzhenyu** [comment]
@qinzuoyan  the travis-ci test seems wired today and I just made some fix at https://github.com/imzhenyu/rDSN/pull/530 . May need to restart the test for this pr again after that pr is merged up to Microsoft/rDSN. 

The last two steps for committing changes to dist.service are unnecessary unless you always work from that repo to include this repo. For me, I have the two repos in different directories. 

```
git clone imzhenyu/rDSN
git clone imzhenyu/rDSN.dist.service
cd rDSN
./run.sh build
./run.sh test
./run.sh install
cd ..
cd rDSN.dist.service
dsn.run.sh build
dsn.run.sh test
```

**Comment by imzhenyu** [comment]
Seems the failure is caused by ```./run.sh stop_zk``` in .travis.yml. You may remove that and try this pr again.

**Comment by qinzuoyan** [comment]
@imzhenyu , where is the script dsn.run.sh?

**Comment by imzhenyu** [comment]
it is under $DSN_ROOT/bin - which is available after rDSN installation.

**Comment by qinzuoyan** [comment]
@imzhenyu , please review it or merge it.

**Pull request merged**
