### PR TITLE
fix ci tests 

### PR DESCRIPTION
**Pull request by imzhenyu**

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , there is compile error in https://travis-ci.org/imzhenyu/rDSN.dist.service/builds/151445856
```
Building CXX object src/meta_server/meta_server_lib/CMakeFiles/dsn.dist.service.meta_server_lib.dir/server_state.o

In file included from /home/travis/build/imzhenyu/rDSN.dist.service/include/dsn/dist/replication/replication_types.h:10:0,

                 from /home/travis/build/imzhenyu/rDSN.dist.service/src/common/replication_types.cpp:7:

/home/travis/build/imzhenyu/rDSN.dist.service/main/include/dsn/cpp/serialization_helper/dsn.layer2_types.h:12:27: fatal error: thrift/Thrift.h: No such file or directory

 #include <thrift/Thrift.h>

                           ^

[ 19%] compilation terminated.
```

**Comment by imzhenyu** [comment]
@qinzuoyan Thanks. It is wired that travis still report success in this case.

**Comment by qinzuoyan** [comment]
@imzhenyu , refer to https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build 
```
Breaking the Build #

If any of the commands in the first four stages of the build lifecycle return a non-zero exit code, the build is broken:

    If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately.
    If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.

The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.
```

**Comment by imzhenyu** [comment]
@qinzuoyan Thanks. 
Now the error is: virtual memory exhausted: Cannot allocate memory, complained by gcc ..

**Comment by imzhenyu** [comment]
Probably because I use ```make -j```, try ```make -j 4`` for another try.

**Comment by imzhenyu** [comment]
Some ZK-related unit test failed on windows; merge for now and will fix later.

**Pull request merged**
